services:
  web:
    build: .
    volumes:
      - ./instance:/app/instance
      - ./flaskr:/app/flaskr:ro
      - ./tests:/app/tests:ro
      - ./requirements.txt:/app/requirements.txt:ro
      - ./.env:/app/.env:ro
    environment:
      - FLASK_APP=app:app
      - FLASK_ENV=development
    ports:
      - "5000:5000"