services:
  web:
    build: .
    volumes:
      - ./flaskr:/app/flaskr:ro
      - ./tests:/app/tests:ro
      - ./requirements.txt:/app/requirements.txt:ro
      - ./.env:/app/.env:ro
      - ./start_container.sh:/app/start_container.sh:ro
    ports:
      - "5000:5000"
