name: DevSecOps CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: CI Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build and start services
        run: docker compose up -d --build

      - name: Wait for app
        run: sleep 5

      - name: Run tests
        run: docker compose exec -T web pytest

      - name: Stop containers
        run: docker compose down

  dast:
    name: DAST with OWASP ZAP
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start application
        run: docker compose up -d --build

      - name: Wait for app to be ready
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:5000 > /dev/null; then
              echo "App is up"
              break
            fi
            echo "Waiting for app..."
            sleep 5
          done

      - name: Run OWASP ZAP DAST scan (Fail on HIGH)
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: 'http://localhost:5000'
          fail_action: true
          rules_file_name: '.zap/rules.tsv'

      - name: Stop application
        run: docker compose down

  container-scan:
    name: Container Security Scan (Trivy)
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t flask-app:latest .

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: flask-app
          format: table
          severity: HIGH,CRITICAL
          exit-code: 1
